layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: britannio
  # mastodon: your_username
  medium: britannio
  # stackoverflow: 6134716
  # telegram: your_username
  twitter: britannioj
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  tiktok: britanniobuilds

# topics:
#   - name: Flutter
#     web_url: https://flutter.dev
#     image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

#   - name: Autonomous Driving

#   - name: hobby 3

#   - name: hobby 4

apps:
  - name: Pic Habits
    client: Britannio
    client_url: https://britannio.com
    short_description: A photo based habit tracker
    technologies:
      - Flutter
      - Dart
    screenshot: pichabits.jpg
    play_store_id: app.pichabits.pichabits
    app_store_id: 6621184172
  # - name: Classify
    # client:
  - name: Reflection.app
    client: Holstee Inc
    client_url: https://holstee.com
    short_description: A better way to journal
    technologies:
      - Flutter
      - Dart
    screenshot: reflection.jpg
    play_store_id: app.reflection.reflection
    app_store_id: 1504547616
    website: https://my.reflection.app
  - name: Covid-19
    client: World Health Organization
    client_url: https://who.int
    short_description: An information app for Covid-19
    technologies:
      - Flutter
      - Dart
    screenshot: covid.jpg
    play_store_id:
    app_store_id:
    source_code: https://github.com/WorldHealthOrganization/app
  - name: Cheon Smart Planner
    short_description: A Smart Study Planner app for students
    technologies:
      - Flutter
      - Dart
    screenshot: cheon.jpg
    play_store_id: app.cheon.app
    app_store_id: 1486076973
    website: https://cheon.app
    source_code: https://github.com/cheon-app/planner
  - name: Solar Sales
    client: Avatara Technologies
    client_url: avataratech.com
    short_description: A map based app for D2D salesperson to manage clients and generate leads.
    technologies:
      - Flutter
      - Dart
    screenshot: solarsales.jpg
    play_store_id: app.solarsales.app
    app_store_id: 1474039079
    website: https://solarsales.app/
  - name: Emrals
    client: Emrals
    client_url: https://emrals.com
    short_description: Earn cryptocurreny for cleaning up rubbish in your area.
    technologies:
      - Flutter
      - Dart
    screenshot: emrals.jpg
    play_store_id: com.apps.emrals
    app_store_id: 1289090169
    website: https://emrals.com
  - name: DIG Impact
    client: Wyrmix LLC
    client_url: http://wyrmix.com
    short_description:
    technologies:
      - Flutter
      - Dart
    screenshot: dig.jpg
  # - name: My Portfolio
  #   short_description:
  #   technologies:
  #     - HTML
  #     - CSS
  #     - Ruby
  #   website: \#
  #   source_code: github.com/britannio/personal-website
  # - name: Amplified.gg
  #   client: Avatara Technologies
  #   client_url: https://avataratech.com
  #   short_description:
  #   technologies:
  #     - Flutter
  #     - Dart
  #     - Java
  #   play_store_id:
  #   app_store_id:
  #   website: https://
  #   source_code: github.com/
